### ISSUE TITLE
Ace editor field needs to be scrollable in the vertical direction

### ISSUE THREAD

**Issue by ScottNeaves** [ScottNeaves/curl-builder#23]
If you put a ton of JSON in there, it starts to become inaccessible below the bottom edge of the field. You'll need to set a CSS property to make it vertically scrollable I believe.

**Comment by bumpylog** [comment]
I am having a difficult time recreating the issue. When I put a lot of JSON in the editor (500+ lines) the scrollbar appears and I am able to scroll vertically.
